"""Write docs/TOWN_DIRECTORY.md (buildings, landmarks, roads) from build/roblox/manifest.json.

    python tools/write_directory.py [manifest.json] [out.md]
"""

import collections
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

LABEL = {
    "house_small": "Small house", "house_medium": "Two-storey house", "house_old": "Old house",
    "house_nice": "Large house", "trailer": "Trailer home", "apartment_lowrise": "Apartment block",
    "convenience_store": "Convenience store", "restaurant": "Restaurant", "diner": "Diner",
    "bar": "Bar", "pawn_shop": "Pawn shop", "laundromat": "Laundromat", "shop": "Shop",
    "office_small": "Office building", "mixed_use": "Shop + apartments",
    "office_tower": "Office tower", "supermarket": "Supermarket", "car_dealership": "Car dealership",
    "auto_shop": "Auto repair", "warehouse": "Warehouse", "warehouse_small": "Workshop",
    "fish_warehouse": "Fish processing plant", "storage_facility": "Self storage",
    "factory": "Cannery", "police_station": "Police station", "fire_station": "Fire station",
    "town_hall": "Town hall", "marina_office": "Marina office", "boat_storage": "Boat storage",
    "waterfront_restaurant": "Waterfront restaurant", "harbor_shed": "Harbor shed",
    "motel": "Motel", "gas_station": "Gas station", "lighthouse": "Lighthouse + radio studio",
    "water_tower": "Water tower + pump house", "parking_structure": "Parking garage",
    "mansion": "Estate",
}

DISTRICTS = [
    ("DOWNTOWN", "Downtown"), ("CIVIC", "Civic Center"), ("MIXED_USE", "Old Town (mixed use)"),
    ("COMMERCIAL", "Route 13 commercial strip"), ("WATERFRONT", "Waterfront & marina"),
    ("INDUSTRIAL", "Industrial / rail yard"), ("LOW_INCOME", "The Flats (low income)"),
    ("MOTEL", "Roadside / motel row"), ("RESIDENTIAL", "Westside residential"),
    ("RESIDENTIAL_N", "North Hill residential"), ("OUTSKIRTS", "Outskirts"),
]


def rb(c):
    """Blender (x, y, z) -> Roblox 'X, Z' text."""
    return f"{c[0]:.0f}, {-c[1]:.0f}"


def main(src, out):
    m = json.load(open(src))
    B = m["buildings"]
    L = []
    w = L.append
    w("# Port Solace - Town Directory")
    w("")
    w("Generated by `blender/tools/write_directory.py` from `build/roblox/manifest.json` "
      "(seed 7). Positions are **Roblox studs** `X, Z` (X = east, -Z = north); every building "
      "also has a `building` marker and entrance markers in the Roblox build.")
    w("")
    s = m["stats"]
    rooms = sum(len(b["rooms"]) for b in B)
    ents = sum(len(b["entrances"]) for b in B)
    w("| Item | Count |")
    w("|---|---|")
    for k, v in (("Buildings (all enterable)", len(B)), ("Rooms", rooms),
                 ("Entrances (doors, bays, gates)", ents),
                 ("Furniture & fixtures inside buildings", s["building_props"]),
                 ("Street / yard / park props", s["world_props"]), ("Trees & plants", s["vegetation"]),
                 ("Light sources", s["lights"]), ("Named roads", s["roads"]),
                 ("Junctions", s["junctions"]),
                 ("Road length", f'{s["road_length"] / 1000:.1f}k studs')):
        w(f"| {k} | {v} |")
    w("")

    # landmarks -----------------------------------------------------------------------
    w("## Landmarks")
    w("")
    w("| Landmark | Position (X, Z) | Height of ground |")
    w("|---|---|---|")
    seen = set()
    for lm in m["landmarks"]:
        if lm["name"] in seen:
            continue
        seen.add(lm["name"])
        p = lm["pos"]
        w(f"| {lm['name'].title() if lm['name'].isupper() else lm['name']} | "
          f"{p[0]:.0f}, {p[2]:.0f} | {p[1]:.0f} |")
    w("")

    # roads ---------------------------------------------------------------------------
    w("## Roads")
    w("")
    w("| Road | Class | Width | Length | Bridge |")
    w("|---|---|---|---|---|")
    for r in m["roads"]:
        w(f"| {r['name']} | {r['kind']} | {r['width']:.0f} | {r['length']:.0f} | "
          f"{'yes' if r['bridge'] else ''} |")
    w("")

    # buildings by district ------------------------------------------------------------
    w("## Buildings by district")
    w("")
    w("Floors count above-ground levels; `B` = basement, `R` = roof access. Entrance roles: "
      "main, secondary, service, loading, garage, staff, vehicle, ...")
    w("")
    by = collections.defaultdict(list)
    for b in B:
        by[b["district"]].append(b)
    for key, title in DISTRICTS:
        bs = by.get(key)
        if not bs:
            continue
        kinds = collections.Counter(LABEL.get(b["archetype"], b["archetype"]) for b in bs)
        w(f"### {title} ({len(bs)} buildings)")
        w("")
        w(", ".join(f"{n} x{c}" for n, c in kinds.most_common()))
        w("")
        w("| ID | Name / address | Type | Floors | Rooms | Entrances | Position (X, Z) |")
        w("|---|---|---|---|---|---|---|")
        for b in sorted(bs, key=lambda b: (not b["landmark"], b["id"])):
            name = b["name"]
            if b.get("address") and b["address"] != name:
                name = f"{name}, {b['address']}"
            if b["landmark"]:
                name = f"**{name}**"
            fl = str(b["levels"]) + (" B" if b["basement"] else "") + (" R" if b["roof_access"]
                                                                       else "")
            roles = collections.Counter(e["role"] for e in b["entrances"])
            ent = ", ".join(f"{r}" + (f" x{c}" if c > 1 else "") for r, c in roles.most_common(4))
            if len(roles) > 4:
                ent += ", ..."
            w(f"| {b['id']} | {name} | {LABEL.get(b['archetype'], b['archetype'])} | {fl} | "
              f"{len(b['rooms'])} | {ent} | {rb(b['center'])} |")
        w("")
    with open(out, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {out} ({len(B)} buildings)")


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build", "roblox",
                                                              "manifest.json")
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "docs", "TOWN_DIRECTORY.md")
    main(src, out)
