"""Generates roblox/MuleSetup.lua, a ModuleScript that finishes the imported
model in Roblox Studio: materials and colours, optional SurfaceAppearance
textures, seats, simple collision boxes, welds and light switching.
"""

import os

from dims import *  # noqa: F401,F403

S = STUDS_PER_METRE


def _v3(x, y, z):
    return f"Vector3.new({x:.3f}, {y:.3f}, {z:.3f})"


def _rel(x, y, z):
    """Blender metres -> studs relative to MuleRoot (centre between the axles at axle height)."""
    return (x * S, (z - AXLE_Z) * S, -y * S)


def _box(name, xmin, xmax, ymin, ymax, zmin, zmax):
    c = _rel((xmin + xmax) / 2, (ymin + ymax) / 2, (zmin + zmax) / 2)
    size = ((xmax - xmin) * S, (zmax - zmin) * S, (ymax - ymin) * S)
    return f'\t{{ Name = "{name}", Offset = {_v3(*c)}, Size = {_v3(*size)} }},'


def colliders():
    w = 0.90
    rows = [
        _box("Collider_Nose", -w, w, 0.80, Y_NOSE, 0.42, 1.20),
        _box("Collider_Cab", -w, w, Y_CAB_BACK, 0.80, 0.47, 1.30),
        _box("Collider_Greenhouse", -0.80, 0.80, Y_RW_BOT, 0.30, 1.30, ROOF_Z),
        _box("Collider_BedFloor", -w, w, Y_BED_BACK, Y_BED_FRONT, 0.60, Z_BED_FLOOR),
        _box("Collider_BedFront", -w, w, Y_BED_FRONT - 0.055, Y_BED_FRONT, 0.60, Z_BED_RAIL),
        _box("Collider_BedLeft", -w, -0.77, Y_BED_BACK, Y_BED_FRONT, 0.60, Z_BED_RAIL),
        _box("Collider_BedRight", 0.77, w, Y_BED_BACK, Y_BED_FRONT, 0.60, Z_BED_RAIL),
        _box("Collider_Tailgate", -w, w, Y_BED_BACK, Y_BED_BACK + 0.055, 0.60, 1.283),
        _box("Collider_RearBumper", -0.86, 0.86, Y_TAIL, Y_BED_BACK + 0.10, 0.47, 0.69),
    ]
    return "\n".join(rows)


LIGHTS = {
    "Head": ["Headlight_DRL_L", "Headlight_DRL_R", "Headlight_Lens_L", "Headlight_Lens_R", "FogLamp_L", "FogLamp_R"],
    "Tail": ["TailLight_Brake_L", "TailLight_Brake_R", "PlateLamp"],
    "Brake": ["TailLight_Brake_L", "TailLight_Brake_R"],
    "Reverse": ["TailLight_Reverse_L", "TailLight_Reverse_R"],
    "TurnLeft": ["Headlight_Indicator_L", "TailLight_Turn_L"],
    "TurnRight": ["Headlight_Indicator_R", "TailLight_Turn_R"],
}

TEXTURE_SETS = {
    "Paint": ("mule_paint_color.png", "mule_paint_roughness.png"),
    "Bedliner": ("mule_bedliner_color.png", "mule_bedliner_roughness.png"),
    "Tire": ("mule_tire_color.png", "mule_tire_roughness.png"),
}


def write_setup_module(data, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mats = []
    for k, m in data["materials"].items():
        r, g, b = m["color_rgb"]
        mats.append(f'\t{k} = {{ Material = Enum.Material.{m["roblox_material"]}, Color = Color3.fromRGB({r}, {g}, {b}), '
                    f'Transparency = {m["transparency"]}, Reflectance = {m["reflectance"]} }},')
    parts = []
    textured = []
    for p in data["parts"]:
        parts.append(f'\t["{p["name"]}"] = "{p["material"]}",')
        tex = p.get("texture_color")
        if tex:
            for setname, (c, _r) in TEXTURE_SETS.items():
                if c == tex:
                    textured.append(f'\t["{p["name"]}"] = "{setname}",')
    lights = []
    for k, names in LIGHTS.items():
        lights.append(f'\t{k} = {{ ' + ", ".join(f'"{n}"' for n in names) + " },")
    texsets = []
    for k, (c, r) in TEXTURE_SETS.items():
        texsets.append(f'\t{k} = {{ ColorMap = "", RoughnessMap = "" }}, -- {c}, {r}')
    seats = []
    for s in data["seats"]:
        kind = "VehicleSeat" if s["name"].endswith("Driver") else "Seat"
        seats.append(f'\t{{ Anchor = "{s["name"]}", Kind = "{kind}" }},')

    src = TEMPLATE
    src = src.replace("%MATERIALS%", "\n".join(mats))
    src = src.replace("%PARTS%", "\n".join(parts))
    src = src.replace("%TEXTURED%", "\n".join(textured))
    src = src.replace("%TEXSETS%", "\n".join(texsets))
    src = src.replace("%LIGHTS%", "\n".join(lights))
    src = src.replace("%SEATS%", "\n".join(seats))
    src = src.replace("%COLLIDERS%", colliders())
    src = src.replace("%TRIS%", str(data["triangles_total"]))
    sz = data["size_studs"]
    src = src.replace("%SIZE%", f'{sz["length"]} x {sz["width_with_mirrors"]} x {sz["height"]}')
    with open(path, "w") as f:
        f.write(src)


TEMPLATE = r'''-- MuleSetup: finishes the imported Mule pickup inside Roblox Studio.
-- Generated by tools/mule/build.py; edit the generator rather than this file.
--
-- Truck: %SIZE% studs (length x width incl. mirrors x height), %TRIS% triangles.
--
-- Usage (server Script, after importing mule_pickup.fbx as a Model):
--     local MuleSetup = require(path.to.MuleSetup)
--     MuleSetup.Setup(workspace.Mule)                   -- materials, seats, colliders, welds
--     MuleSetup.SetLights(workspace.Mule, { Head = true, Tail = true })
--
-- Setup() is idempotent: running it twice leaves one set of seats/colliders/welds.

local MuleSetup = {}

-- Roblox material, colour (sRGB) and transparency per palette key.
MuleSetup.Materials = {
%MATERIALS%
}

-- Imported part name -> palette key.
MuleSetup.PartMaterials = {
%PARTS%
}

-- Optional wear textures. Upload the PNGs in textures/ as Images and paste
-- their rbxassetid:// ids here; parts listed in TexturedParts then get a
-- SurfaceAppearance (dust, grime, roughness variation).
MuleSetup.Textures = {
%TEXSETS%
}

MuleSetup.TexturedParts = {
%TEXTURED%
}

MuleSetup.Lights = {
%LIGHTS%
}

-- The driver gets a VehicleSeat; the other three are plain Seats.
MuleSetup.Seats = {
%SEATS%
}

-- Invisible collision boxes, offsets in studs from MuleRoot (centre between
-- the axles at axle height; -Z is the front of the truck). The visual
-- meshes stay CanCollide = false so physics stays cheap and the bed is a
-- flat, walkable floor.
MuleSetup.Colliders = {
%COLLIDERS%
}

local function find(model, name)
	return model:FindFirstChild(name, true)
end

local function ensureRoot(model)
	local root = find(model, "MuleRoot")
	if root == nil then
		error("MuleSetup: MuleRoot part not found in " .. model:GetFullName())
	end
	root.Transparency = 1
	root.CanCollide = false
	root.CanQuery = false
	root.CanTouch = false
	root.Massless = false
	model.PrimaryPart = root
	return root
end

function MuleSetup.ApplyMaterials(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("BasePart") and inst.Name ~= "MuleRoot" then
			local key = MuleSetup.PartMaterials[inst.Name]
			local m = key and MuleSetup.Materials[key]
			if m then
				inst.Material = m.Material
				inst.Color = m.Color
				inst.Transparency = m.Transparency
				inst.Reflectance = m.Reflectance
				inst:SetAttribute("MuleMaterial", key)
			end
			inst.CanCollide = false
			inst.CanTouch = false
			inst.Massless = true
			if inst.Size.Magnitude < 1.5 then
				inst.CastShadow = false
			end
		end
	end
end

function MuleSetup.ApplyTextures(model)
	for partName, setName in pairs(MuleSetup.TexturedParts) do
		local set = MuleSetup.Textures[setName]
		local part = find(model, partName)
		if set and set.ColorMap ~= "" and part and part:IsA("MeshPart") then
			local sa = part:FindFirstChildOfClass("SurfaceAppearance")
			if sa == nil then
				sa = Instance.new("SurfaceAppearance")
				sa.Parent = part
			end
			sa.ColorMap = set.ColorMap
			if set.RoughnessMap ~= "" then
				sa.RoughnessMap = set.RoughnessMap
			end
		end
	end
end

function MuleSetup.CreateSeats(model)
	for _, spec in ipairs(MuleSetup.Seats) do
		local anchor = find(model, spec.Anchor)
		local seatName = string.gsub(spec.Anchor, "SeatAnchor_", "Seat_")
		if anchor and find(model, seatName) == nil then
			local seat = Instance.new(spec.Kind)
			seat.Name = seatName
			seat.Size = anchor.Size
			seat.CFrame = anchor.CFrame
			seat.Transparency = 1
			seat.CanCollide = false
			seat.Anchored = false
			seat.Massless = true
			seat.Parent = anchor.Parent
			anchor:Destroy()
		end
	end
end

function MuleSetup.CreateColliders(model)
	local root = ensureRoot(model)
	local folder = model:FindFirstChild("Colliders")
	if folder == nil then
		folder = Instance.new("Folder")
		folder.Name = "Colliders"
		folder.Parent = model
	end
	for _, c in ipairs(MuleSetup.Colliders) do
		if folder:FindFirstChild(c.Name) == nil then
			local p = Instance.new("Part")
			p.Name = c.Name
			p.Size = c.Size
			p.CFrame = root.CFrame * CFrame.new(c.Offset)
			p.Transparency = 1
			p.CanCollide = true
			p.CanQuery = true
			p.Anchored = false
			p.Parent = folder
		end
	end
end

-- Welds every part to MuleRoot. Pass skipWheels = true when a chassis
-- (A-Chassis or your own) drives the Wheel_* models itself.
function MuleSetup.Weld(model, skipWheels)
	local root = ensureRoot(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("BasePart") and inst ~= root then
			local inWheel = false
			if skipWheels then
				local parent = inst.Parent
				while parent and parent ~= model do
					if string.sub(parent.Name, 1, 6) == "Wheel_" then
						inWheel = true
						break
					end
					parent = parent.Parent
				end
			end
			if not inWheel and inst:FindFirstChild("MuleWeld") == nil then
				local w = Instance.new("WeldConstraint")
				w.Name = "MuleWeld"
				w.Part0 = root
				w.Part1 = inst
				w.Parent = inst
			end
			inst.Anchored = false
		end
	end
end

-- The front plate is the Two-Faced Car upgrade; hide it until it is bought.
function MuleSetup.SetFrontPlate(model, visible)
	for _, name in ipairs({ "Plate_Front", "PlateBracket_Front" }) do
		local p = find(model, name)
		if p then
			p.Transparency = visible and 0 or 1
		end
	end
end

local function addLight(part, className, props)
	local l = part:FindFirstChild("MuleLight")
	if l == nil then
		l = Instance.new(className)
		l.Name = "MuleLight"
		for k, v in pairs(props) do
			l[k] = v
		end
		l.Enabled = false
		l.Parent = part
	end
	return l
end

-- state: { Head = bool, Tail = bool, Brake = bool, Reverse = bool, TurnLeft = bool, TurnRight = bool }
function MuleSetup.SetLights(model, state)
	local lit = {}
	for group, names in pairs(MuleSetup.Lights) do
		if state[group] then
			for _, n in ipairs(names) do
				lit[n] = true
			end
		end
	end
	for _, names in pairs(MuleSetup.Lights) do
		for _, n in ipairs(names) do
			local part = find(model, n)
			if part then
				local key = MuleSetup.PartMaterials[n]
				local base = key and MuleSetup.Materials[key]
				if lit[n] then
					part.Material = Enum.Material.Neon
					part.Transparency = 0
				elseif base then
					part.Material = base.Material
					part.Transparency = base.Transparency
				end
				local light = nil
				if n == "Headlight_Lens_L" or n == "Headlight_Lens_R" then
					light = addLight(part, "SpotLight", { Face = Enum.NormalId.Front, Angle = 70, Range = 60, Brightness = 3, Color = Color3.fromRGB(255, 244, 220) })
				elseif n == "TailLight_Brake_L" or n == "TailLight_Brake_R" then
					light = addLight(part, "PointLight", { Range = 6, Brightness = 1, Color = Color3.fromRGB(255, 40, 30) })
				elseif n == "TailLight_Reverse_L" or n == "TailLight_Reverse_R" then
					light = addLight(part, "SpotLight", { Face = Enum.NormalId.Back, Angle = 90, Range = 18, Brightness = 1.5, Color = Color3.fromRGB(255, 255, 255) })
				end
				if light then
					light.Enabled = lit[n] == true
				end
			end
		end
	end
end

-- Run once from the Studio command bar right after importing; collision
-- fidelity cannot be changed by game scripts. Box collision keeps the 120
-- visual meshes cheap (the Colliders folder does the real collision).
--   require(<path>.MuleSetup).StudioPrep(workspace.Mule)
function MuleSetup.StudioPrep(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("MeshPart") then
			pcall(function()
				inst.CollisionFidelity = Enum.CollisionFidelity.Box
			end)
		end
	end
end

-- options: { seats = true, colliders = true, weld = true, skipWheels = false, frontPlate = false }
function MuleSetup.Setup(model, options)
	options = options or {}
	local function opt(name, default)
		if options[name] == nil then
			return default
		end
		return options[name]
	end
	ensureRoot(model)
	MuleSetup.ApplyMaterials(model)
	MuleSetup.ApplyTextures(model)
	if opt("seats", true) then
		MuleSetup.CreateSeats(model)
	end
	if opt("colliders", true) then
		MuleSetup.CreateColliders(model)
	end
	MuleSetup.SetFrontPlate(model, opt("frontPlate", false))
	MuleSetup.SetLights(model, {})
	if opt("weld", true) then
		MuleSetup.Weld(model, opt("skipWheels", false))
	end
	return model
end

return MuleSetup
'''
