-- MuleSetup: finishes the imported Mule pickup inside Roblox Studio.
-- Generated by tools/mule/build.py; edit the generator rather than this file.
--
-- Truck: 22.45 x 9.42 x 7.7 studs (length x width incl. mirrors x height), 97178 triangles.
--
-- Usage (server Script, after importing mule_pickup.fbx as a Model):
--     local MuleSetup = require(path.to.MuleSetup)
--     MuleSetup.Setup(workspace.Mule)                   -- materials, seats, colliders, welds
--     MuleSetup.SetLights(workspace.Mule, { Head = true, Tail = true })
--
-- Setup() is idempotent: running it twice leaves one set of seats/colliders/welds.

local MuleSetup = {}

-- Roblox material, colour (sRGB) and transparency per palette key.
MuleSetup.Materials = {
	Paint = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(216, 214, 207), Transparency = 0.0, Reflectance = 0.0 },
	TrimBlack = { Material = Enum.Material.Plastic, Color = Color3.fromRGB(31, 32, 34), Transparency = 0.0, Reflectance = 0.0 },
	TrimDark = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(43, 45, 48), Transparency = 0.0, Reflectance = 0.0 },
	Chrome = { Material = Enum.Material.Metal, Color = Color3.fromRGB(180, 184, 188), Transparency = 0.0, Reflectance = 0.15 },
	Gunmetal = { Material = Enum.Material.Metal, Color = Color3.fromRGB(74, 77, 81), Transparency = 0.0, Reflectance = 0.0 },
	Rubber = { Material = Enum.Material.Rubber, Color = Color3.fromRGB(27, 27, 28), Transparency = 0.0, Reflectance = 0.0 },
	Glass = { Material = Enum.Material.Glass, Color = Color3.fromRGB(46, 53, 57), Transparency = 0.45, Reflectance = 0.05 },
	LensClear = { Material = Enum.Material.Glass, Color = Color3.fromRGB(213, 220, 226), Transparency = 0.6, Reflectance = 0.05 },
	LensRed = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(140, 28, 28), Transparency = 0.1, Reflectance = 0.0 },
	LensAmber = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(194, 105, 15), Transparency = 0.1, Reflectance = 0.0 },
	LensWhite = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(228, 229, 226), Transparency = 0.05, Reflectance = 0.0 },
	LightDRL = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(243, 245, 248), Transparency = 0.0, Reflectance = 0.0 },
	MirrorGlass = { Material = Enum.Material.Glass, Color = Color3.fromRGB(142, 149, 155), Transparency = 0.0, Reflectance = 0.6 },
	Bedliner = { Material = Enum.Material.Plastic, Color = Color3.fromRGB(40, 41, 43), Transparency = 0.0, Reflectance = 0.0 },
	WheelWell = { Material = Enum.Material.Plastic, Color = Color3.fromRGB(25, 25, 26), Transparency = 0.0, Reflectance = 0.0 },
	Underbody = { Material = Enum.Material.Plastic, Color = Color3.fromRGB(42, 43, 45), Transparency = 0.0, Reflectance = 0.0 },
	InteriorTrim = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(58, 60, 63), Transparency = 0.0, Reflectance = 0.0 },
	DoorTrim = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(78, 81, 85), Transparency = 0.0, Reflectance = 0.0 },
	Headliner = { Material = Enum.Material.Fabric, Color = Color3.fromRGB(93, 95, 99), Transparency = 0.0, Reflectance = 0.0 },
	FloorRubber = { Material = Enum.Material.Rubber, Color = Color3.fromRGB(28, 29, 31), Transparency = 0.0, Reflectance = 0.0 },
	Dash = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(42, 44, 47), Transparency = 0.0, Reflectance = 0.0 },
	SeatFabric = { Material = Enum.Material.Fabric, Color = Color3.fromRGB(46, 48, 51), Transparency = 0.0, Reflectance = 0.0 },
	MetalAccent = { Material = Enum.Material.Metal, Color = Color3.fromRGB(139, 143, 148), Transparency = 0.0, Reflectance = 0.0 },
	Screen = { Material = Enum.Material.Glass, Color = Color3.fromRGB(13, 15, 17), Transparency = 0.0, Reflectance = 0.1 },
	Gauge = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(201, 205, 210), Transparency = 0.0, Reflectance = 0.0 },
	RimPaint = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(38, 39, 42), Transparency = 0.0, Reflectance = 0.0 },
	BrakeDisc = { Material = Enum.Material.Metal, Color = Color3.fromRGB(108, 110, 112), Transparency = 0.0, Reflectance = 0.0 },
	Plate = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(236, 236, 230), Transparency = 0.0, Reflectance = 0.0 },
	Anchor = { Material = Enum.Material.SmoothPlastic, Color = Color3.fromRGB(79, 163, 255), Transparency = 1.0, Reflectance = 0.0 },
}

-- Imported part name -> palette key.
MuleSetup.PartMaterials = {
	["Badge_Front"] = "Chrome",
	["Body_Bed"] = "Paint",
	["Body_Bed_Bedliner"] = "Bedliner",
	["Body_Bed_TrimBlack"] = "TrimBlack",
	["Body_Bed_Underbody"] = "Underbody",
	["Body_Bed_WheelWell"] = "WheelWell",
	["Body_Cab"] = "Paint",
	["Body_Cab_FloorRubber"] = "FloorRubber",
	["Body_Cab_Headliner"] = "Headliner",
	["Body_Cab_InteriorTrim"] = "InteriorTrim",
	["Body_Cab_TrimBlack"] = "TrimBlack",
	["Body_Cab_TrimDark"] = "TrimDark",
	["Body_Cab_Underbody"] = "Underbody",
	["Body_Cab_WheelWell"] = "WheelWell",
	["Bumper_Front"] = "Paint",
	["Bumper_Front_Lower"] = "TrimBlack",
	["Bumper_Front_WheelWell"] = "WheelWell",
	["Bumper_Rear"] = "Gunmetal",
	["Bumper_Rear_Caps"] = "TrimBlack",
	["Bumper_Rear_Step"] = "Rubber",
	["Console"] = "Dash",
	["Cowl"] = "TrimBlack",
	["Dash_Controls"] = "TrimBlack",
	["Dash_Gauges"] = "Gauge",
	["Dash_Needles"] = "LensAmber",
	["Dash_Screen"] = "Screen",
	["Dash_Vents"] = "TrimBlack",
	["Dashboard"] = "Dash",
	["DomeLight"] = "LensWhite",
	["DoorHandles_L"] = "TrimBlack",
	["DoorHandles_R"] = "TrimBlack",
	["Door_FL"] = "Paint",
	["Door_FL_DoorTrim"] = "DoorTrim",
	["Door_FL_Glass"] = "Glass",
	["Door_FL_InnerHandle"] = "MetalAccent",
	["Door_FL_TrimBlack"] = "TrimBlack",
	["Door_FR"] = "Paint",
	["Door_FR_DoorTrim"] = "DoorTrim",
	["Door_FR_Glass"] = "Glass",
	["Door_FR_InnerHandle"] = "MetalAccent",
	["Door_FR_TrimBlack"] = "TrimBlack",
	["Door_RL"] = "Paint",
	["Door_RL_DoorTrim"] = "DoorTrim",
	["Door_RL_Glass"] = "Glass",
	["Door_RL_InnerHandle"] = "MetalAccent",
	["Door_RL_TrimBlack"] = "TrimBlack",
	["Door_RR"] = "Paint",
	["Door_RR_DoorTrim"] = "DoorTrim",
	["Door_RR_Glass"] = "Glass",
	["Door_RR_InnerHandle"] = "MetalAccent",
	["Door_RR_TrimBlack"] = "TrimBlack",
	["Exhaust"] = "Gunmetal",
	["FogBezel_L"] = "TrimBlack",
	["FogBezel_R"] = "TrimBlack",
	["FogLamp_L"] = "LensWhite",
	["FogLamp_R"] = "LensWhite",
	["FuelDoor"] = "Paint",
	["GearShifter"] = "TrimBlack",
	["Glass_Rear"] = "Glass",
	["Glass_Windshield"] = "Glass",
	["Glovebox"] = "Dash",
	["Grille"] = "TrimDark",
	["Handbrake"] = "TrimBlack",
	["Headlight_DRL_L"] = "LightDRL",
	["Headlight_DRL_R"] = "LightDRL",
	["Headlight_Housing_L"] = "Gunmetal",
	["Headlight_Housing_R"] = "Gunmetal",
	["Headlight_Indicator_L"] = "LensAmber",
	["Headlight_Indicator_R"] = "LensAmber",
	["Headlight_Lens_L"] = "LensClear",
	["Headlight_Lens_R"] = "LensClear",
	["Headlight_Reflector_L"] = "Chrome",
	["Headlight_Reflector_R"] = "Chrome",
	["Hood"] = "Paint",
	["Mirror_Glass_L"] = "MirrorGlass",
	["Mirror_Glass_R"] = "MirrorGlass",
	["Mirror_L"] = "TrimBlack",
	["Mirror_R"] = "TrimBlack",
	["MudFlap_FL"] = "Rubber",
	["MudFlap_FR"] = "Rubber",
	["MudFlap_RL"] = "Rubber",
	["MudFlap_RR"] = "Rubber",
	["MuleRoot"] = "Anchor",
	["Pedals"] = "TrimBlack",
	["PlateBracket_Front"] = "TrimBlack",
	["PlateLamp"] = "LensWhite",
	["Plate_Front"] = "Plate",
	["Plate_Rear"] = "Plate",
	["RearViewMirror"] = "TrimBlack",
	["RearViewMirror_Glass"] = "MirrorGlass",
	["SeatAnchor_Driver"] = "Anchor",
	["SeatAnchor_Passenger"] = "Anchor",
	["SeatAnchor_RearLeft"] = "Anchor",
	["SeatAnchor_RearRight"] = "Anchor",
	["Seat_Front_L"] = "SeatFabric",
	["Seat_Front_L_Base"] = "InteriorTrim",
	["Seat_Front_R"] = "SeatFabric",
	["Seat_Front_R_Base"] = "InteriorTrim",
	["Seat_Rear"] = "SeatFabric",
	["SkidPlate"] = "Gunmetal",
	["SpareWheel_Tire"] = "Rubber",
	["SteeringColumn"] = "TrimBlack",
	["SteeringWheel"] = "TrimBlack",
	["SunVisor_L"] = "DoorTrim",
	["SunVisor_R"] = "DoorTrim",
	["TailLight_Brake_L"] = "LensRed",
	["TailLight_Brake_R"] = "LensRed",
	["TailLight_Reverse_L"] = "LensWhite",
	["TailLight_Reverse_R"] = "LensWhite",
	["TailLight_Turn_L"] = "LensAmber",
	["TailLight_Turn_R"] = "LensAmber",
	["Tailgate"] = "Paint",
	["Tailgate_Bedliner"] = "Bedliner",
	["Tailgate_Handle"] = "TrimBlack",
	["Tailgate_TrimBlack"] = "TrimBlack",
	["Underbody_Chassis"] = "Underbody",
	["Wheel_FL_Caliper"] = "Gunmetal",
	["Wheel_FL_Disc"] = "BrakeDisc",
	["Wheel_FL_Rim"] = "RimPaint",
	["Wheel_FL_Tire"] = "Rubber",
	["Wheel_FR_Caliper"] = "Gunmetal",
	["Wheel_FR_Disc"] = "BrakeDisc",
	["Wheel_FR_Rim"] = "RimPaint",
	["Wheel_FR_Tire"] = "Rubber",
	["Wheel_RL_Drum"] = "Gunmetal",
	["Wheel_RL_Rim"] = "RimPaint",
	["Wheel_RL_Tire"] = "Rubber",
	["Wheel_RR_Drum"] = "Gunmetal",
	["Wheel_RR_Rim"] = "RimPaint",
	["Wheel_RR_Tire"] = "Rubber",
	["Wipers"] = "TrimBlack",
}

-- Optional wear textures. Upload the PNGs in textures/ as Images and paste
-- their rbxassetid:// ids here; parts listed in TexturedParts then get a
-- SurfaceAppearance (dust, grime, roughness variation).
MuleSetup.Textures = {
	Paint = { ColorMap = "", RoughnessMap = "" }, -- mule_paint_color.png, mule_paint_roughness.png
	Bedliner = { ColorMap = "", RoughnessMap = "" }, -- mule_bedliner_color.png, mule_bedliner_roughness.png
	Tire = { ColorMap = "", RoughnessMap = "" }, -- mule_tire_color.png, mule_tire_roughness.png
}

MuleSetup.TexturedParts = {
	["Body_Bed"] = "Paint",
	["Body_Bed_Bedliner"] = "Bedliner",
	["Body_Cab"] = "Paint",
	["Bumper_Front"] = "Paint",
	["Door_FL"] = "Paint",
	["Door_FR"] = "Paint",
	["Door_RL"] = "Paint",
	["Door_RR"] = "Paint",
	["FuelDoor"] = "Paint",
	["Hood"] = "Paint",
	["SpareWheel_Tire"] = "Tire",
	["Tailgate"] = "Paint",
	["Tailgate_Bedliner"] = "Bedliner",
	["Wheel_FL_Tire"] = "Tire",
	["Wheel_FR_Tire"] = "Tire",
	["Wheel_RL_Tire"] = "Tire",
	["Wheel_RR_Tire"] = "Tire",
}

MuleSetup.Lights = {
	Head = { "Headlight_DRL_L", "Headlight_DRL_R", "Headlight_Lens_L", "Headlight_Lens_R", "FogLamp_L", "FogLamp_R" },
	Tail = { "TailLight_Brake_L", "TailLight_Brake_R", "PlateLamp" },
	Brake = { "TailLight_Brake_L", "TailLight_Brake_R" },
	Reverse = { "TailLight_Reverse_L", "TailLight_Reverse_R" },
	TurnLeft = { "Headlight_Indicator_L", "TailLight_Turn_L" },
	TurnRight = { "Headlight_Indicator_R", "TailLight_Turn_R" },
}

-- The driver gets a VehicleSeat; the other three are plain Seats.
MuleSetup.Seats = {
	{ Anchor = "SeatAnchor_Driver", Kind = "VehicleSeat" },
	{ Anchor = "SeatAnchor_Passenger", Kind = "Seat" },
	{ Anchor = "SeatAnchor_RearLeft", Kind = "Seat" },
	{ Anchor = "SeatAnchor_RearRight", Kind = "Seat" },
}

-- Invisible collision boxes, offsets in studs from MuleRoot (centre between
-- the axles at axle height; -Z is the front of the truck). The visual
-- meshes stay CanCollide = false so physics stays cheap and the bed is a
-- flat, walkable floor.
MuleSetup.Colliders = {
	{ Name = "Collider_Nose", Offset = Vector3.new(0.000, 1.827, -6.901), Size = Vector3.new(7.650, 3.315, 7.002) },
	{ Name = "Collider_Cab", Offset = Vector3.new(0.000, 2.146, 0.606), Size = Vector3.new(7.650, 3.528, 8.011) },
	{ Name = "Collider_Greenhouse", Offset = Vector3.new(0.000, 4.983, 1.636), Size = Vector3.new(6.800, 2.146, 5.823) },
	{ Name = "Collider_BedFloor", Offset = Vector3.new(0.000, 1.402, 8.287), Size = Vector3.new(7.650, 0.935, 7.012) },
	{ Name = "Collider_BedFront", Offset = Vector3.new(0.000, 2.401, 4.898), Size = Vector3.new(7.650, 2.933, 0.234) },
	{ Name = "Collider_BedLeft", Offset = Vector3.new(-3.549, 2.401, 8.287), Size = Vector3.new(0.552, 2.933, 7.012) },
	{ Name = "Collider_BedRight", Offset = Vector3.new(3.549, 2.401, 8.287), Size = Vector3.new(0.552, 2.933, 7.012) },
	{ Name = "Collider_Tailgate", Offset = Vector3.new(0.000, 2.386, 11.677), Size = Vector3.new(7.650, 2.903, 0.234) },
	{ Name = "Collider_RearBumper", Offset = Vector3.new(0.000, 0.850, 11.703), Size = Vector3.new(7.310, 0.935, 0.669) },
}

local function find(model, name)
	return model:FindFirstChild(name, true)
end

local function ensureRoot(model)
	local root = find(model, "MuleRoot")
	if root == nil then
		error("MuleSetup: MuleRoot part not found in " .. model:GetFullName())
	end
	root.Transparency = 1
	root.CanCollide = false
	root.CanQuery = false
	root.CanTouch = false
	root.Massless = false
	model.PrimaryPart = root
	return root
end

function MuleSetup.ApplyMaterials(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("BasePart") and inst.Name ~= "MuleRoot" then
			local key = MuleSetup.PartMaterials[inst.Name]
			local m = key and MuleSetup.Materials[key]
			if m then
				inst.Material = m.Material
				inst.Color = m.Color
				inst.Transparency = m.Transparency
				inst.Reflectance = m.Reflectance
				inst:SetAttribute("MuleMaterial", key)
			end
			inst.CanCollide = false
			inst.CanTouch = false
			inst.Massless = true
			if inst.Size.Magnitude < 1.5 then
				inst.CastShadow = false
			end
		end
	end
end

function MuleSetup.ApplyTextures(model)
	for partName, setName in pairs(MuleSetup.TexturedParts) do
		local set = MuleSetup.Textures[setName]
		local part = find(model, partName)
		if set and set.ColorMap ~= "" and part and part:IsA("MeshPart") then
			local sa = part:FindFirstChildOfClass("SurfaceAppearance")
			if sa == nil then
				sa = Instance.new("SurfaceAppearance")
				sa.Parent = part
			end
			sa.ColorMap = set.ColorMap
			if set.RoughnessMap ~= "" then
				sa.RoughnessMap = set.RoughnessMap
			end
		end
	end
end

function MuleSetup.CreateSeats(model)
	for _, spec in ipairs(MuleSetup.Seats) do
		local anchor = find(model, spec.Anchor)
		local seatName = string.gsub(spec.Anchor, "SeatAnchor_", "Seat_")
		if anchor and find(model, seatName) == nil then
			local seat = Instance.new(spec.Kind)
			seat.Name = seatName
			seat.Size = anchor.Size
			seat.CFrame = anchor.CFrame
			seat.Transparency = 1
			seat.CanCollide = false
			seat.Anchored = false
			seat.Massless = true
			seat.Parent = anchor.Parent
			anchor:Destroy()
		end
	end
end

function MuleSetup.CreateColliders(model)
	local root = ensureRoot(model)
	local folder = model:FindFirstChild("Colliders")
	if folder == nil then
		folder = Instance.new("Folder")
		folder.Name = "Colliders"
		folder.Parent = model
	end
	for _, c in ipairs(MuleSetup.Colliders) do
		if folder:FindFirstChild(c.Name) == nil then
			local p = Instance.new("Part")
			p.Name = c.Name
			p.Size = c.Size
			p.CFrame = root.CFrame * CFrame.new(c.Offset)
			p.Transparency = 1
			p.CanCollide = true
			p.CanQuery = true
			p.Anchored = false
			p.Parent = folder
		end
	end
end

-- Welds every part to MuleRoot. Pass skipWheels = true when a chassis
-- (A-Chassis or your own) drives the Wheel_* models itself.
function MuleSetup.Weld(model, skipWheels)
	local root = ensureRoot(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("BasePart") and inst ~= root then
			local inWheel = false
			if skipWheels then
				local parent = inst.Parent
				while parent and parent ~= model do
					if string.sub(parent.Name, 1, 6) == "Wheel_" then
						inWheel = true
						break
					end
					parent = parent.Parent
				end
			end
			if not inWheel and inst:FindFirstChild("MuleWeld") == nil then
				local w = Instance.new("WeldConstraint")
				w.Name = "MuleWeld"
				w.Part0 = root
				w.Part1 = inst
				w.Parent = inst
			end
			inst.Anchored = false
		end
	end
end

-- The front plate is the Two-Faced Car upgrade; hide it until it is bought.
function MuleSetup.SetFrontPlate(model, visible)
	for _, name in ipairs({ "Plate_Front", "PlateBracket_Front" }) do
		local p = find(model, name)
		if p then
			p.Transparency = visible and 0 or 1
		end
	end
end

local function addLight(part, className, props)
	local l = part:FindFirstChild("MuleLight")
	if l == nil then
		l = Instance.new(className)
		l.Name = "MuleLight"
		for k, v in pairs(props) do
			l[k] = v
		end
		l.Enabled = false
		l.Parent = part
	end
	return l
end

-- state: { Head = bool, Tail = bool, Brake = bool, Reverse = bool, TurnLeft = bool, TurnRight = bool }
function MuleSetup.SetLights(model, state)
	local lit = {}
	for group, names in pairs(MuleSetup.Lights) do
		if state[group] then
			for _, n in ipairs(names) do
				lit[n] = true
			end
		end
	end
	for _, names in pairs(MuleSetup.Lights) do
		for _, n in ipairs(names) do
			local part = find(model, n)
			if part then
				local key = MuleSetup.PartMaterials[n]
				local base = key and MuleSetup.Materials[key]
				if lit[n] then
					part.Material = Enum.Material.Neon
					part.Transparency = 0
				elseif base then
					part.Material = base.Material
					part.Transparency = base.Transparency
				end
				local light = nil
				if n == "Headlight_Lens_L" or n == "Headlight_Lens_R" then
					light = addLight(part, "SpotLight", { Face = Enum.NormalId.Front, Angle = 70, Range = 60, Brightness = 3, Color = Color3.fromRGB(255, 244, 220) })
				elseif n == "TailLight_Brake_L" or n == "TailLight_Brake_R" then
					light = addLight(part, "PointLight", { Range = 6, Brightness = 1, Color = Color3.fromRGB(255, 40, 30) })
				elseif n == "TailLight_Reverse_L" or n == "TailLight_Reverse_R" then
					light = addLight(part, "SpotLight", { Face = Enum.NormalId.Back, Angle = 90, Range = 18, Brightness = 1.5, Color = Color3.fromRGB(255, 255, 255) })
				end
				if light then
					light.Enabled = lit[n] == true
				end
			end
		end
	end
end

-- Run once from the Studio command bar right after importing; collision
-- fidelity cannot be changed by game scripts. Box collision keeps the 120
-- visual meshes cheap (the Colliders folder does the real collision).
--   require(<path>.MuleSetup).StudioPrep(workspace.Mule)
function MuleSetup.StudioPrep(model)
	for _, inst in ipairs(model:GetDescendants()) do
		if inst:IsA("MeshPart") then
			pcall(function()
				inst.CollisionFidelity = Enum.CollisionFidelity.Box
			end)
		end
	end
end

-- options: { seats = true, colliders = true, weld = true, skipWheels = false, frontPlate = false }
function MuleSetup.Setup(model, options)
	options = options or {}
	local function opt(name, default)
		if options[name] == nil then
			return default
		end
		return options[name]
	end
	ensureRoot(model)
	MuleSetup.ApplyMaterials(model)
	MuleSetup.ApplyTextures(model)
	if opt("seats", true) then
		MuleSetup.CreateSeats(model)
	end
	if opt("colliders", true) then
		MuleSetup.CreateColliders(model)
	end
	MuleSetup.SetFrontPlate(model, opt("frontPlate", false))
	MuleSetup.SetLights(model, {})
	if opt("weld", true) then
		MuleSetup.Weld(model, opt("skipWheels", false))
	end
	return model
end

return MuleSetup
